name: conan2 ubuntu-latest Debug

on:
  push:
    branches: [ "xmake" ]
  pull_request:
    branches: [ "xmake" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install conan2
        run: |
          echo "ubuntu version"
          lsb_release -a
          hostnamectl
          uname -a
          echo "cpuinfo"
          cat /proc/cpuinfo
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install conan==2.6.0
          conan profile detect
          echo "conan2 profiles"
          cat ~/.conan2/profiles/default
          sed -i 's/Release/Debug/g' ~/.conan2/profiles/default
          sed -i 's/gnu14/gnu17/g' ~/.conan2/profiles/default
          echo "conan2 profiles"
          cat ~/.conan2/profiles/default
          conan remote update conancenter --url https://center2.conan.io
          echo "conan remote list"
          conan remote list

      - name: conan build
        run: |
          echo "cmake version"
          cmake --version
          #        mkdir temp
          #        cd temp
          #        wget -O cmake.tar.gz https://cmake.org/files/v3.24/cmake-3.24.4-linux-x86_64.tar.gz
          #        tar zxvf cmake.tar.gz -C ./
          #        export PATH=./temp/cmake-3.24.4-linux-x86_64/bin:$PATH
          #        echo "cmake --version"
          #        cmake --version
          #        cd ..
          #        conan profile list
          conan install . --build=missing -pr=default
          cmake --preset conan-debug
          cmake --build ${{github.workspace}}/build/Debug --config ${{env.BUILD_TYPE}}  -j 3